/**
 * Canonical internal architecture graph for Assistant-MK1.
 *
 * This is the source of truth for generated architecture views. Keep graph
 * schema shape and graph content together here while the renderer handles only
 * validation and output. Maintainers should not need to edit another graph
 * source file when adding nodes, edges, kinds, tags, or views.
 *
 * Update this file when a change affects a tracked file/doc responsibility,
 * runtime boundary, durable contract, workflow, policy, storage ownership, or
 * current/target status. Then run `pnpm graph:render` and `pnpm graph:check`.
 */

export const architectureNodeKinds = [
  "app",
  "runtime",
  "api_route",
  "component",
  "interface",
  "entity",
  "workflow",
  "policy",
  "storage",
  "tooling",
  "doc",
  "config",
  "external",
] as const;

export const architectureEdgeKinds = [
  "calls",
  "proxies_to",
  "renders",
  "owns",
  "reads",
  "writes",
  "emits",
  "enforces",
  "streams_to",
  "derives_scope",
  "stores",
  "documents",
  "configures",
  "generates",
  "must_not_access",
] as const;

export type ArchitectureNodeKind = (typeof architectureNodeKinds)[number];

export type ArchitectureEdgeKind = (typeof architectureEdgeKinds)[number];

export type ArchitectureNode = {
  id: string;
  label: string;
  summary: string;
  kind: ArchitectureNodeKind;
  tags: string[];
  fileRefs?: string[];
  notes?: string;
};

export type ArchitectureEdge = {
  id: string;
  from: string;
  to: string;
  kind: ArchitectureEdgeKind;
  label: string;
  tags?: string[];
  notes?: string;
};

export type ArchitectureView = {
  id: string;
  title: string;
  summary: string;
  nodeIds: string[];
  edgeIds: string[];
  direction?: "LR" | "TD";
};

export type ArchitectureGraph = {
  id: string;
  title: string;
  summary: string;
  nodes: ArchitectureNode[];
  edges: ArchitectureEdge[];
  views: ArchitectureView[];
};

function defineArchitectureGraph(graph: ArchitectureGraph): ArchitectureGraph {
  return graph;
}

const current = ["current"] as const;
const target = ["target", "planned"] as const;

export const architectureGraph = defineArchitectureGraph({
  id: "assistant-mk1-architecture",
  title: "Assistant-MK1 Internal Architecture Graph",
  summary:
    "Developer-facing map of the current assistant-ui LangGraph starter and the target reusable agent workbench architecture.",
  nodes: [
    {
      id: "assistant-mk1",
      label: "Assistant-MK1 Workbench",
      summary: "Reusable agent workbench built from the assistant-ui LangGraph starter.",
      kind: "app",
      tags: [...current, "workbench", "root"],
      fileRefs: ["README.md", "goal.md"],
    },
    {
      id: "next-app",
      label: "Next.js App Router",
      summary: "Current web app runtime that serves the assistant UI and API routes.",
      kind: "runtime",
      tags: [...current, "frontend", "api"],
      fileRefs: ["app/layout.tsx", "app/page.tsx", "next.config.ts"],
    },
    {
      id: "home-route",
      label: "Home Route",
      summary: "Renders the first-screen assistant experience.",
      kind: "app",
      tags: [...current, "frontend"],
      fileRefs: ["app/page.tsx"],
    },
    {
      id: "assistant-runtime",
      label: "assistant-ui LangGraph Runtime",
      summary:
        "Client bridge that creates the LangGraph SDK client and streams assistant-ui messages through LangGraph runs.",
      kind: "runtime",
      tags: [...current, "frontend", "streaming", "langgraph"],
      fileRefs: ["app/assistant.tsx"],
    },
    {
      id: "thread-ui",
      label: "Thread UI Composition",
      summary:
        "Main assistant conversation surface composed from assistant-ui primitives and local renderers.",
      kind: "component",
      tags: [...current, "frontend", "assistant-ui"],
      fileRefs: ["components/assistant-ui/thread.tsx"],
    },
    {
      id: "attachment-ui",
      label: "Attachment UI",
      summary: "Composer and message attachment controls for assistant-ui interactions.",
      kind: "component",
      tags: [...current, "frontend", "assistant-ui", "artifacts"],
      fileRefs: ["components/assistant-ui/attachment.tsx"],
    },
    {
      id: "markdown-ui",
      label: "Markdown Renderer",
      summary: "GFM-capable renderer for assistant messages and reasoning content.",
      kind: "component",
      tags: [...current, "frontend", "assistant-ui"],
      fileRefs: ["components/assistant-ui/markdown-text.tsx"],
    },
    {
      id: "reasoning-ui",
      label: "Reasoning Renderer",
      summary: "Inspectable collapsible reasoning display for assistant-ui stream parts.",
      kind: "component",
      tags: [...current, "frontend", "assistant-ui", "reasoning"],
      fileRefs: ["components/assistant-ui/reasoning.tsx"],
    },
    {
      id: "tool-call-ui",
      label: "Tool Call UI",
      summary: "Generic inspectable rendering for streaming tool call state and outputs.",
      kind: "component",
      tags: [...current, "frontend", "assistant-ui", "tools"],
      fileRefs: [
        "components/assistant-ui/tool-group.tsx",
        "components/assistant-ui/tool-fallback.tsx",
      ],
    },
    {
      id: "ui-primitives",
      label: "Local UI Primitives",
      summary:
        "Reusable shadcn-style primitives for buttons, dialogs, avatars, tooltips, and collapsibles.",
      kind: "component",
      tags: [...current, "frontend", "ui"],
      fileRefs: [
        "components/ui/avatar.tsx",
        "components/ui/button.tsx",
        "components/ui/collapsible.tsx",
        "components/ui/dialog.tsx",
        "components/ui/tooltip.tsx",
        "lib/utils.ts",
      ],
    },
    {
      id: "chat-client",
      label: "LangGraph SDK Client Factory",
      summary: "Creates browser-facing LangGraph SDK clients that use the Next proxy by default.",
      kind: "interface",
      tags: [...current, "frontend", "langgraph", "network"],
      fileRefs: ["lib/chatApi.ts"],
    },
    {
      id: "api-proxy",
      label: "LangGraph API Proxy",
      summary:
        "Catch-all Next route that forwards browser SDK traffic to the LangGraph API server.",
      kind: "api_route",
      tags: [...current, "server", "langgraph", "proxy"],
      fileRefs: ["app/api/[..._path]/route.ts"],
    },
    {
      id: "external-signals-route",
      label: "External Signals Route",
      summary: "Bearer-token protected route for external starts, resumes, and cron creation.",
      kind: "api_route",
      tags: [...current, "server", "external-trigger", "langgraph"],
      fileRefs: ["app/api/external-signals/route.ts"],
    },
    {
      id: "health-route",
      label: "Health Route",
      summary: "Lightweight runtime health endpoint for local and Fly staging checks.",
      kind: "api_route",
      tags: [...current, "server", "health"],
      fileRefs: ["app/api/health/route.ts"],
    },
    {
      id: "langgraph-backend",
      label: "LangGraph Backend Graph",
      summary: "Current graph provider seam that invokes the configured OpenRouter chat model.",
      kind: "runtime",
      tags: [...current, "server", "langgraph", "model-provider"],
      fileRefs: ["backend/agent.ts", "langgraph.json"],
    },
    {
      id: "openrouter-provider",
      label: "OpenRouter Provider",
      summary: "Server-side model provider configured by backend environment variables.",
      kind: "external",
      tags: [...current, "model-provider", "server-secret"],
      fileRefs: ["backend/agent.ts", ".env.example"],
    },
    {
      id: "langgraph-config",
      label: "LangGraph Config",
      summary: "Maps graph id `agent` to the compiled backend graph for local/Fly execution.",
      kind: "config",
      tags: [...current, "langgraph", "config"],
      fileRefs: ["langgraph.json"],
    },
    {
      id: "fly-staging",
      label: "Fly Dev/Staging Runtime",
      summary:
        "Current hosted staging target that can run Next and LangGraph together in one Machine.",
      kind: "runtime",
      tags: [...current, "staging", "fly", "deployment"],
      fileRefs: ["Dockerfile", "fly.toml"],
    },
    {
      id: "package-scripts",
      label: "Package Scripts",
      summary: "Local development, typecheck, lint, build, and graph tooling entrypoints.",
      kind: "tooling",
      tags: [...current, "tooling", "developer-experience"],
      fileRefs: ["package.json", "pnpm-lock.yaml"],
    },
    {
      id: "framework-contracts",
      label: "Framework Runtime Contracts",
      summary:
        "Small provisional runtime types for tenant scope, policies, tools, intents, and refs.",
      kind: "interface",
      tags: [...current, "contracts", "runtime", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "durable-entity-contracts",
      label: "Durable Entity Contracts",
      summary: "Serializable entity record types for future canonical state.",
      kind: "interface",
      tags: [...current, "contracts", "state", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "data-client-contract",
      label: "AgentFrameworkDataClient",
      summary:
        "Repository-style interface for workflow reads/writes without committing to storage.",
      kind: "interface",
      tags: [...current, "contracts", "state", "repository", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/data-client.ts"],
    },
    {
      id: "decision-record",
      label: "DecisionRecordEntity",
      summary: "Durable reasoning/provenance record for beliefs, strategies, plans, and decisions.",
      kind: "entity",
      tags: [...current, "entity", "state", "provenance", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "audit-event",
      label: "AuditEventRecord",
      summary: "Append-only record of important platform, workflow, or tool activity.",
      kind: "entity",
      tags: [...current, "entity", "state", "audit", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "artifact-metadata",
      label: "ArtifactMetadataRecord",
      summary: "Searchable metadata for files, logs, traces, screenshots, reports, and exports.",
      kind: "entity",
      tags: [...current, "entity", "state", "artifacts", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "workflow-intent",
      label: "WorkflowIntentRecord",
      summary: "Typed escalation request from chat, schedule, webhook, or trusted event.",
      kind: "entity",
      tags: [...current, "entity", "workflow", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "run-record",
      label: "RunRecord",
      summary: "Runtime control record for foreground, background, workflow, and child executions.",
      kind: "entity",
      tags: [...current, "entity", "workflow", "runtime", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "tool-call-record",
      label: "ToolCallRecord",
      summary: "One auditable execution attempt against a registered tool.",
      kind: "entity",
      tags: [...current, "entity", "tools", "audit", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "managed-state",
      label: "ManagedStateRecord",
      summary: "Domain asset the agent owns, monitors, or explains.",
      kind: "entity",
      tags: [...current, "entity", "state", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "ledger-entry",
      label: "LedgerEntryRecord",
      summary:
        "Durable proposed, simulated, executed, skipped, blocked, or reviewed action record.",
      kind: "entity",
      tags: [...current, "entity", "ledger", "audit", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "trigger-record",
      label: "TriggerRecord",
      summary: "Schedule, webhook, external event, or tool event that can wake work.",
      kind: "entity",
      tags: [...current, "entity", "trigger", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "tool-metadata",
      label: "Tool Metadata and Permission Records",
      summary: "Serializable tool registry metadata and tenant-scoped enablement policy.",
      kind: "entity",
      tags: [...current, "entity", "tools", "policy", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/db-contracts.ts"],
    },
    {
      id: "cloudflare-control-plane",
      label: "Cloudflare Control Plane",
      summary:
        "Target live multi-user coordination layer for streams, schedules, triggers, state access, and policy checks.",
      kind: "runtime",
      tags: [...target, "control-plane", "tenant-scoped", "streaming"],
    },
    {
      id: "fly-tool-runners",
      label: "Fly Tool Runners",
      summary:
        "Target heavy execution plane for CLIs, OSS packages, browser automation, and LangGraph workers.",
      kind: "runtime",
      tags: [...target, "execution-plane", "fly", "tools"],
    },
    {
      id: "langgraph-workflow-service",
      label: "LangGraph Workflow Service",
      summary:
        "Target complex workflow engine behind typed escalation, interrupts, and resumability.",
      kind: "runtime",
      tags: [...target, "execution-plane", "langgraph", "workflow"],
    },
    {
      id: "policy-layer",
      label: "Policy Layer",
      summary:
        "Validates tenant scope, execution mode, permissions, approvals, limits, and kill switches.",
      kind: "policy",
      tags: [...target, "policy", "security", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "secret-custody",
      label: "Secret Custody",
      summary: "Encrypted, scoped, revocable, server-side credential custody for approved tools.",
      kind: "policy",
      tags: [...target, "security", "secrets", "server-only"],
    },
    {
      id: "tenant-scope",
      label: "Tenant Scope",
      summary:
        "Trusted `userId + workspaceId` context applied to durable state, tools, artifacts, and triggers.",
      kind: "policy",
      tags: [...current, "tenant-scoped", "security"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "execution-policy",
      label: "Execution Policy",
      summary:
        "Deterministic ask, dry-run, execute mode plus policy references for approval and limits.",
      kind: "policy",
      tags: [...current, "policy", "tools", "security"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "tool-exposure-resolver",
      label: "Tool Exposure Resolver",
      summary: "Narrows registered tools to the model-visible set for a scoped run context.",
      kind: "policy",
      tags: [...current, "policy", "tools", "tenant-scoped"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "lifecycle-events",
      label: "Lifecycle Events",
      summary: "Typed runtime events for audit, UI timelines, policy checks, and future hooks.",
      kind: "workflow",
      tags: [...current, "workflow", "audit", "extension"],
      fileRefs: ["lib/agent-framework/contracts.ts"],
    },
    {
      id: "d1-storage",
      label: "D1 Relational State",
      summary:
        "Target relational control-plane store for tenant records, decisions, audit, ledgers, and metadata.",
      kind: "storage",
      tags: [...target, "storage", "d1", "state"],
    },
    {
      id: "r2-storage",
      label: "R2 Artifact Storage",
      summary: "Target object store for blobs, logs, reports, screenshots, traces, and exports.",
      kind: "storage",
      tags: [...target, "storage", "r2", "artifacts"],
    },
    {
      id: "durable-object-state",
      label: "Durable Object Hot State",
      summary:
        "Target per-agent hot coordination state, locks, active sessions, and wakeup metadata.",
      kind: "storage",
      tags: [...target, "storage", "durable-object", "coordination"],
    },
    {
      id: "workflow-backend-state",
      label: "Workflow Backend State",
      summary:
        "In-flight workflow checkpoints, retries, interrupts, and step state owned by the workflow engine.",
      kind: "storage",
      tags: [...target, "storage", "workflow", "langgraph"],
    },
    {
      id: "workflow-lifecycle",
      label: "Workflow Lifecycle",
      summary:
        "Generic observe, analyze, propose, execute, review lifecycle used across reference apps.",
      kind: "workflow",
      tags: [...current, "workflow", "generic"],
    },
    {
      id: "observe-stage",
      label: "Observe",
      summary: "Collect state, events, inputs, or external data.",
      kind: "workflow",
      tags: [...current, "workflow-stage"],
    },
    {
      id: "analyze-stage",
      label: "Analyze",
      summary: "Compare evidence, reason about options, and update conviction.",
      kind: "workflow",
      tags: [...current, "workflow-stage"],
    },
    {
      id: "propose-stage",
      label: "Propose",
      summary: "Create an action proposal, plan, or recommendation.",
      kind: "workflow",
      tags: [...current, "workflow-stage"],
    },
    {
      id: "execute-stage",
      label: "Execute",
      summary: "Perform an approved action or dry-run execution.",
      kind: "workflow",
      tags: [...current, "workflow-stage", "policy-gated"],
    },
    {
      id: "review-stage",
      label: "Review",
      summary: "Inspect results, update managed state, and write durable outputs.",
      kind: "workflow",
      tags: [...current, "workflow-stage"],
    },
    {
      id: "signed-tool-call",
      label: "Signed Tool Call Boundary",
      summary: "Target signed, typed, tenant-scoped request from control plane to execution plane.",
      kind: "interface",
      tags: [...target, "tools", "security", "tenant-scoped"],
    },
    {
      id: "external-trigger",
      label: "External Trigger",
      summary:
        "Webhook, schedule, tool event, or outside system signal that wakes the correct workspace.",
      kind: "external",
      tags: [...current, "trigger", "external"],
      fileRefs: ["app/api/external-signals/route.ts"],
    },
    {
      id: "docs-architecture",
      label: "Architecture Docs",
      summary:
        "Repo-native Markdown docs for system shape, infrastructure, runtime, data, and risk boundaries.",
      kind: "doc",
      tags: [...current, "docs"],
    },
    {
      id: "reference-apps",
      label: "Reference App Docs",
      summary:
        "Polymancer and deployment-agent mappings that stress-test generic framework primitives.",
      kind: "doc",
      tags: [...current, "docs", "reference-app"],
    },
    {
      id: "architecture-graph-tooling",
      label: "Architecture Graph Tooling",
      summary:
        "Typed graph schema, canonical graph source, and renderer for generated Markdown/Mermaid views.",
      kind: "tooling",
      tags: [...current, "docs", "graph-as-code", "developer-experience"],
      fileRefs: ["docs/architecture.graph.ts", "scripts/render-architecture-graph.ts"],
    },
  ],
  edges: [
    {
      id: "assistant-mk1-uses-next-app",
      from: "assistant-mk1",
      to: "next-app",
      kind: "owns",
      label: "current app runtime",
    },
    {
      id: "next-renders-home",
      from: "next-app",
      to: "home-route",
      kind: "renders",
      label: "serves",
    },
    {
      id: "home-renders-assistant",
      from: "home-route",
      to: "assistant-runtime",
      kind: "renders",
      label: "renders",
    },
    {
      id: "assistant-renders-thread",
      from: "assistant-runtime",
      to: "thread-ui",
      kind: "renders",
      label: "provides runtime",
    },
    {
      id: "thread-renders-attachments",
      from: "thread-ui",
      to: "attachment-ui",
      kind: "renders",
      label: "renders",
    },
    {
      id: "thread-renders-markdown",
      from: "thread-ui",
      to: "markdown-ui",
      kind: "renders",
      label: "renders",
    },
    {
      id: "thread-renders-reasoning",
      from: "thread-ui",
      to: "reasoning-ui",
      kind: "renders",
      label: "renders",
    },
    {
      id: "thread-renders-tool-calls",
      from: "thread-ui",
      to: "tool-call-ui",
      kind: "renders",
      label: "renders",
    },
    {
      id: "assistant-uses-chat-client",
      from: "assistant-runtime",
      to: "chat-client",
      kind: "calls",
      label: "creates SDK client",
    },
    {
      id: "chat-client-calls-api-proxy",
      from: "chat-client",
      to: "api-proxy",
      kind: "calls",
      label: "browser SDK traffic",
    },
    {
      id: "api-proxy-proxies-langgraph",
      from: "api-proxy",
      to: "langgraph-backend",
      kind: "proxies_to",
      label: "forwards API requests",
    },
    {
      id: "external-signals-calls-langgraph",
      from: "external-signals-route",
      to: "langgraph-backend",
      kind: "calls",
      label: "starts, resumes, creates crons",
    },
    {
      id: "external-trigger-calls-route",
      from: "external-trigger",
      to: "external-signals-route",
      kind: "calls",
      label: "authenticated signal",
    },
    {
      id: "health-documents-staging-wiring",
      from: "health-route",
      to: "fly-staging",
      kind: "documents",
      label: "smoke target",
    },
    {
      id: "langgraph-config-configures-backend",
      from: "langgraph-config",
      to: "langgraph-backend",
      kind: "configures",
      label: "graph id agent",
    },
    {
      id: "langgraph-backend-calls-openrouter",
      from: "langgraph-backend",
      to: "openrouter-provider",
      kind: "calls",
      label: "model invoke",
    },
    {
      id: "frontend-must-not-access-provider",
      from: "assistant-runtime",
      to: "openrouter-provider",
      kind: "must_not_access",
      label: "provider secrets stay server-side",
    },
    {
      id: "fly-staging-runs-next",
      from: "fly-staging",
      to: "next-app",
      kind: "owns",
      label: "runs in staging",
    },
    {
      id: "fly-staging-runs-langgraph",
      from: "fly-staging",
      to: "langgraph-backend",
      kind: "owns",
      label: "runs in staging",
    },
    {
      id: "framework-contracts-define-scope",
      from: "framework-contracts",
      to: "tenant-scope",
      kind: "documents",
      label: "defines",
    },
    {
      id: "framework-contracts-define-policy",
      from: "framework-contracts",
      to: "execution-policy",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-decisions",
      from: "durable-entity-contracts",
      to: "decision-record",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-audit",
      from: "durable-entity-contracts",
      to: "audit-event",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-artifacts",
      from: "durable-entity-contracts",
      to: "artifact-metadata",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-intents",
      from: "durable-entity-contracts",
      to: "workflow-intent",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-runs",
      from: "durable-entity-contracts",
      to: "run-record",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-tool-calls",
      from: "durable-entity-contracts",
      to: "tool-call-record",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-managed-state",
      from: "durable-entity-contracts",
      to: "managed-state",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-ledger",
      from: "durable-entity-contracts",
      to: "ledger-entry",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-trigger",
      from: "durable-entity-contracts",
      to: "trigger-record",
      kind: "documents",
      label: "defines",
    },
    {
      id: "durable-contracts-define-tool-metadata",
      from: "durable-entity-contracts",
      to: "tool-metadata",
      kind: "documents",
      label: "defines",
    },
    {
      id: "data-client-writes-decisions",
      from: "data-client-contract",
      to: "decision-record",
      kind: "writes",
      label: "create, list, supersede",
    },
    {
      id: "data-client-writes-audit",
      from: "data-client-contract",
      to: "audit-event",
      kind: "writes",
      label: "append",
    },
    {
      id: "data-client-writes-artifacts",
      from: "data-client-contract",
      to: "artifact-metadata",
      kind: "writes",
      label: "metadata, upload URL",
    },
    {
      id: "data-client-writes-intents",
      from: "data-client-contract",
      to: "workflow-intent",
      kind: "writes",
      label: "create, update status",
    },
    {
      id: "data-client-writes-runs",
      from: "data-client-contract",
      to: "run-record",
      kind: "writes",
      label: "create, update, list",
    },
    {
      id: "data-client-writes-tool-calls",
      from: "data-client-contract",
      to: "tool-call-record",
      kind: "writes",
      label: "started, finished",
    },
    {
      id: "data-client-writes-managed-state",
      from: "data-client-contract",
      to: "managed-state",
      kind: "writes",
      label: "get, patch",
    },
    {
      id: "data-client-writes-ledger",
      from: "data-client-contract",
      to: "ledger-entry",
      kind: "writes",
      label: "append, list",
    },
    {
      id: "data-client-enforces-scope",
      from: "data-client-contract",
      to: "tenant-scope",
      kind: "enforces",
      label: "scope first argument",
    },
    {
      id: "cloudflare-owns-stream",
      from: "cloudflare-control-plane",
      to: "assistant-runtime",
      kind: "streams_to",
      label: "target user-facing stream",
    },
    {
      id: "cloudflare-owns-data-client",
      from: "cloudflare-control-plane",
      to: "data-client-contract",
      kind: "owns",
      label: "initial mediated implementation",
    },
    {
      id: "cloudflare-derives-scope",
      from: "cloudflare-control-plane",
      to: "tenant-scope",
      kind: "derives_scope",
      label: "auth or trusted trigger context",
    },
    {
      id: "cloudflare-enforces-policy",
      from: "cloudflare-control-plane",
      to: "policy-layer",
      kind: "enforces",
      label: "before escalation",
    },
    {
      id: "cloudflare-creates-intents",
      from: "cloudflare-control-plane",
      to: "workflow-intent",
      kind: "writes",
      label: "typed escalation",
    },
    {
      id: "cloudflare-updates-runs",
      from: "cloudflare-control-plane",
      to: "run-record",
      kind: "writes",
      label: "status and heartbeat",
    },
    {
      id: "cloudflare-calls-fly",
      from: "cloudflare-control-plane",
      to: "fly-tool-runners",
      kind: "calls",
      label: "signed server request",
    },
    {
      id: "cloudflare-calls-langgraph-workflows",
      from: "cloudflare-control-plane",
      to: "langgraph-workflow-service",
      kind: "calls",
      label: "workflow escalation",
    },
    {
      id: "fly-uses-data-client",
      from: "fly-tool-runners",
      to: "data-client-contract",
      kind: "calls",
      label: "scoped reads/writes",
    },
    {
      id: "langgraph-service-uses-data-client",
      from: "langgraph-workflow-service",
      to: "data-client-contract",
      kind: "calls",
      label: "scoped reads/writes",
    },
    {
      id: "signed-tool-call-targets-fly",
      from: "signed-tool-call",
      to: "fly-tool-runners",
      kind: "calls",
      label: "typed execution request",
    },
    {
      id: "policy-enforces-execution-policy",
      from: "policy-layer",
      to: "execution-policy",
      kind: "enforces",
      label: "ask, dry-run, execute",
    },
    {
      id: "policy-enforces-tool-exposure",
      from: "policy-layer",
      to: "tool-exposure-resolver",
      kind: "enforces",
      label: "model-visible tools",
    },
    {
      id: "policy-enforces-secret-custody",
      from: "policy-layer",
      to: "secret-custody",
      kind: "enforces",
      label: "approved tools only",
    },
    {
      id: "secret-custody-must-not-browser",
      from: "assistant-runtime",
      to: "secret-custody",
      kind: "must_not_access",
      label: "browser never receives secrets",
    },
    {
      id: "d1-stores-entities",
      from: "d1-storage",
      to: "durable-entity-contracts",
      kind: "stores",
      label: "target relational records",
    },
    {
      id: "r2-stores-artifacts",
      from: "r2-storage",
      to: "artifact-metadata",
      kind: "stores",
      label: "blob backing store",
    },
    {
      id: "durable-object-stores-hot-state",
      from: "durable-object-state",
      to: "cloudflare-control-plane",
      kind: "stores",
      label: "hot coordination state",
    },
    {
      id: "workflow-backend-stores-checkpoints",
      from: "workflow-backend-state",
      to: "langgraph-workflow-service",
      kind: "stores",
      label: "in-flight execution state",
    },
    {
      id: "workflow-emits-lifecycle-events",
      from: "workflow-lifecycle",
      to: "lifecycle-events",
      kind: "emits",
      label: "runtime events",
    },
    {
      id: "workflow-starts-observe",
      from: "workflow-lifecycle",
      to: "observe-stage",
      kind: "owns",
      label: "stage",
    },
    {
      id: "observe-to-analyze",
      from: "observe-stage",
      to: "analyze-stage",
      kind: "emits",
      label: "evidence",
    },
    {
      id: "analyze-to-propose",
      from: "analyze-stage",
      to: "propose-stage",
      kind: "emits",
      label: "options",
    },
    {
      id: "propose-to-execute",
      from: "propose-stage",
      to: "execute-stage",
      kind: "emits",
      label: "approved or dry-run action",
    },
    {
      id: "execute-to-review",
      from: "execute-stage",
      to: "review-stage",
      kind: "emits",
      label: "result",
    },
    {
      id: "review-writes-decisions",
      from: "review-stage",
      to: "decision-record",
      kind: "writes",
      label: "why and provenance",
    },
    {
      id: "review-writes-audit",
      from: "review-stage",
      to: "audit-event",
      kind: "writes",
      label: "activity trail",
    },
    {
      id: "review-writes-ledger",
      from: "review-stage",
      to: "ledger-entry",
      kind: "writes",
      label: "action record",
    },
    {
      id: "review-writes-managed-state",
      from: "review-stage",
      to: "managed-state",
      kind: "writes",
      label: "updated asset state",
    },
    {
      id: "tool-execution-writes-tool-call",
      from: "fly-tool-runners",
      to: "tool-call-record",
      kind: "writes",
      label: "execution attempt",
    },
    {
      id: "tool-execution-writes-artifact",
      from: "fly-tool-runners",
      to: "artifact-metadata",
      kind: "writes",
      label: "logs and outputs",
    },
    {
      id: "tool-execution-writes-audit",
      from: "fly-tool-runners",
      to: "audit-event",
      kind: "writes",
      label: "audit summary",
    },
    {
      id: "lifecycle-events-write-audit",
      from: "lifecycle-events",
      to: "audit-event",
      kind: "writes",
      label: "audit timeline",
    },
    {
      id: "trigger-creates-intent",
      from: "external-trigger",
      to: "workflow-intent",
      kind: "emits",
      label: "wake work",
    },
    {
      id: "trigger-uses-scope",
      from: "external-trigger",
      to: "tenant-scope",
      kind: "derives_scope",
      label: "trusted metadata",
    },
    {
      id: "docs-describe-current-system",
      from: "docs-architecture",
      to: "assistant-mk1",
      kind: "documents",
      label: "system source of truth",
    },
    {
      id: "reference-apps-stress-contracts",
      from: "reference-apps",
      to: "durable-entity-contracts",
      kind: "documents",
      label: "generic mappings",
    },
    {
      id: "reference-apps-stress-policy",
      from: "reference-apps",
      to: "policy-layer",
      kind: "documents",
      label: "mutation gates",
    },
    {
      id: "graph-tooling-documents-system",
      from: "architecture-graph-tooling",
      to: "assistant-mk1",
      kind: "documents",
      label: "generated views",
    },
    {
      id: "package-scripts-run-graph-tooling",
      from: "package-scripts",
      to: "architecture-graph-tooling",
      kind: "calls",
      label: "graph scripts",
    },
  ],
  views: [
    {
      id: "whole-system-overview",
      title: "Whole-System Overview",
      summary: "Current frontend/backend plus target control plane, execution plane, and storage.",
      direction: "LR",
      nodeIds: [
        "assistant-mk1",
        "next-app",
        "home-route",
        "assistant-runtime",
        "cloudflare-control-plane",
        "fly-tool-runners",
        "langgraph-workflow-service",
        "data-client-contract",
        "durable-entity-contracts",
        "run-record",
        "artifact-metadata",
        "d1-storage",
        "r2-storage",
        "durable-object-state",
        "workflow-backend-state",
      ],
      edgeIds: [
        "assistant-mk1-uses-next-app",
        "home-renders-assistant",
        "cloudflare-owns-stream",
        "cloudflare-calls-fly",
        "cloudflare-calls-langgraph-workflows",
        "cloudflare-owns-data-client",
        "fly-uses-data-client",
        "langgraph-service-uses-data-client",
        "data-client-writes-runs",
        "d1-stores-entities",
        "r2-stores-artifacts",
        "durable-object-stores-hot-state",
        "workflow-backend-stores-checkpoints",
      ],
    },
    {
      id: "current-repo-map",
      title: "Current Repo Map",
      summary: "Checked-in app routes, backend graph, components, contracts, and config.",
      direction: "LR",
      nodeIds: [
        "next-app",
        "home-route",
        "assistant-runtime",
        "thread-ui",
        "attachment-ui",
        "markdown-ui",
        "reasoning-ui",
        "tool-call-ui",
        "ui-primitives",
        "chat-client",
        "api-proxy",
        "external-signals-route",
        "health-route",
        "langgraph-backend",
        "openrouter-provider",
        "langgraph-config",
        "framework-contracts",
        "durable-entity-contracts",
        "data-client-contract",
        "run-record",
        "tool-exposure-resolver",
        "lifecycle-events",
        "assistant-mk1",
      ],
      edgeIds: [
        "next-renders-home",
        "home-renders-assistant",
        "assistant-renders-thread",
        "thread-renders-attachments",
        "thread-renders-markdown",
        "thread-renders-reasoning",
        "thread-renders-tool-calls",
        "assistant-uses-chat-client",
        "chat-client-calls-api-proxy",
        "api-proxy-proxies-langgraph",
        "external-signals-calls-langgraph",
        "langgraph-config-configures-backend",
        "langgraph-backend-calls-openrouter",
        "frontend-must-not-access-provider",
        "durable-contracts-define-runs",
      ],
    },
    {
      id: "target-runtime-map",
      title: "Target Runtime Map",
      summary: "Cloudflare owns coordination and streams; Fly/LangGraph execute heavy workflows.",
      direction: "LR",
      nodeIds: [
        "assistant-runtime",
        "cloudflare-control-plane",
        "tenant-scope",
        "policy-layer",
        "workflow-intent",
        "run-record",
        "tool-exposure-resolver",
        "lifecycle-events",
        "signed-tool-call",
        "fly-tool-runners",
        "langgraph-workflow-service",
        "data-client-contract",
        "audit-event",
        "artifact-metadata",
      ],
      edgeIds: [
        "cloudflare-owns-stream",
        "cloudflare-derives-scope",
        "cloudflare-enforces-policy",
        "cloudflare-creates-intents",
        "cloudflare-updates-runs",
        "policy-enforces-tool-exposure",
        "cloudflare-calls-fly",
        "cloudflare-calls-langgraph-workflows",
        "signed-tool-call-targets-fly",
        "fly-uses-data-client",
        "langgraph-service-uses-data-client",
        "tool-execution-writes-audit",
        "tool-execution-writes-artifact",
      ],
    },
    {
      id: "data-and-state-map",
      title: "Data And State Map",
      summary:
        "Repository operations mapped to durable entities and backing storage responsibilities.",
      direction: "LR",
      nodeIds: [
        "data-client-contract",
        "tenant-scope",
        "durable-entity-contracts",
        "decision-record",
        "audit-event",
        "artifact-metadata",
        "workflow-intent",
        "run-record",
        "tool-call-record",
        "managed-state",
        "ledger-entry",
        "d1-storage",
        "r2-storage",
      ],
      edgeIds: [
        "data-client-enforces-scope",
        "data-client-writes-decisions",
        "data-client-writes-audit",
        "data-client-writes-artifacts",
        "data-client-writes-intents",
        "data-client-writes-runs",
        "data-client-writes-tool-calls",
        "data-client-writes-managed-state",
        "data-client-writes-ledger",
        "d1-stores-entities",
        "r2-stores-artifacts",
      ],
    },
    {
      id: "workflow-lifecycle-map",
      title: "Workflow Lifecycle Map",
      summary: "Generic observe/analyze/propose/execute/review flow and durable outputs.",
      direction: "LR",
      nodeIds: [
        "workflow-lifecycle",
        "observe-stage",
        "analyze-stage",
        "propose-stage",
        "execute-stage",
        "review-stage",
        "run-record",
        "lifecycle-events",
        "decision-record",
        "audit-event",
        "ledger-entry",
        "managed-state",
      ],
      edgeIds: [
        "workflow-starts-observe",
        "observe-to-analyze",
        "analyze-to-propose",
        "propose-to-execute",
        "execute-to-review",
        "workflow-emits-lifecycle-events",
        "lifecycle-events-write-audit",
        "review-writes-decisions",
        "review-writes-audit",
        "review-writes-ledger",
        "review-writes-managed-state",
      ],
    },
    {
      id: "tool-execution-map",
      title: "Tool Execution Map",
      summary: "Policy-gated tool request, Fly execution, and audit/artifact persistence.",
      direction: "LR",
      nodeIds: [
        "cloudflare-control-plane",
        "policy-layer",
        "execution-policy",
        "tool-exposure-resolver",
        "signed-tool-call",
        "fly-tool-runners",
        "tool-call-record",
        "artifact-metadata",
        "audit-event",
      ],
      edgeIds: [
        "cloudflare-enforces-policy",
        "policy-enforces-execution-policy",
        "policy-enforces-tool-exposure",
        "cloudflare-calls-fly",
        "signed-tool-call-targets-fly",
        "tool-execution-writes-tool-call",
        "tool-execution-writes-artifact",
        "tool-execution-writes-audit",
      ],
    },
    {
      id: "tenancy-security-map",
      title: "Tenancy And Security Map",
      summary: "Scope derivation, policy enforcement, secret custody, and browser boundaries.",
      direction: "LR",
      nodeIds: [
        "assistant-runtime",
        "external-trigger",
        "cloudflare-control-plane",
        "tenant-scope",
        "data-client-contract",
        "policy-layer",
        "execution-policy",
        "tool-exposure-resolver",
        "secret-custody",
        "openrouter-provider",
      ],
      edgeIds: [
        "trigger-uses-scope",
        "cloudflare-derives-scope",
        "data-client-enforces-scope",
        "cloudflare-enforces-policy",
        "policy-enforces-execution-policy",
        "policy-enforces-tool-exposure",
        "policy-enforces-secret-custody",
        "secret-custody-must-not-browser",
        "frontend-must-not-access-provider",
      ],
    },
  ],
});
